### ISSUE TITLE
Fails to load

### ISSUE THREAD

**Issue by aurel-g** [toxicwind/ComfyUI-TTools#3]
Hi,

I got this error at ComfyUI startup:

```
Launching ComfyUI from: /mnt/comfyui/app

Total VRAM 16073 MB, total RAM 32000 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /mnt/comfyui/app/web
Traceback (most recent call last):
  File "/mnt/comfyui/app/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/comfyui/app/custom_nodes/ComfyUI-TTools/__init__.py", line 16, in <module>
    nlp = spacy.load("en_core_web_sm")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/comfyui/env/python3.11/0566ad298e40625adc9477f5f6b7ce0f/lib/python3.11/site-packages/spacy/__init__.py", line 51, in load
    return util.load_model(
           ^^^^^^^^^^^^^^^^
  File "/mnt/comfyui/env/python3.11/0566ad298e40625adc9477f5f6b7ce0f/lib/python3.11/site-packages/spacy/util.py", line 472, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

Cannot import /mnt/comfyui/app/custom_nodes/ComfyUI-TTools module for custom nodes: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

Import times for custom nodes:
   0.0 seconds: /mnt/comfyui/app/custom_nodes/websocket_image_save.py
   0.3 seconds (IMPORT FAILED): /mnt/comfyui/app/custom_nodes/ComfyUI-TTools
```

**Comment by aurel-g** [comment]
It is probably due to the fact I cant install the pip package "spacy-lang-en". Are we sure this package exists ?
